
--CREATE DATABASE BDJURIDICO 

--USE BDJURIDICO

CREATE TABLE ESTADO 
(
ESTID INT IDENTITY(1,1)PRIMARY KEY,
ESTDESCRICAO VARCHAR(100) NOT NULL,
ESTSIGLA VARCHAR(2) NOT NULL UNIQUE
)
SELECT * FROM ESTADO

--INSERT ESTADO (ESTDESCRICAO,ESTSIGLA) VALUES ('SERGIPE' , 'SE')
INSERT ESTADO (ESTDESCRICAO,ESTSIGLA) VALUES ('SÃO PAULO' , 'SP')
INSERT ESTADO (ESTDESCRICAO,ESTSIGLA) VALUES ('RORAIMA' , 'RR')
INSERT ESTADO VALUES ('BAHIA' , 'BA')
INSERT ESTADO VALUES ('ACRE' , 'AC')

--FILTRAR
SELECT * FROM ESTADO WHERE ESTID=2

UPDATE ESTADO
SET ESTDESCRICAO= 'SAO PAULO', ESTSIGLA= 'PP'
WHERE ESTID=2

DELETE ESTADO
WHERE ESTID=13

--FILTROS 
SELECT * FROM ESTADO
WHERE ESTDESCRICAO LIKE 'S%'

SELECT * FROM ESTADO
WHERE ESTID > 3

SELECT * FROM ESTADO
WHERE ESTID=3 OR ESTID=12

SELECT * FROM ESTADO
WHERE ESTID IN (1,2)

SELECT ESTDESCRICAO, ESTSIGLA FROM ESTADO
WHERE ESTID IN (3,2)

SELECT * FROM ESTADO
WHERE ESTID !=

